// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package datapath

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type netkerEndpoint struct {
	_           structs.HostLayout
	Ifindex     uint32
	PeerIfindex uint32
	Netid       uint32
	Flags       uint32
	Mac         [6]uint8
	PeerMac     [6]uint8
}

type netkerMetricsKey struct {
	_       structs.HostLayout
	Ifindex uint32
	Dir     uint8
	Reason  uint8
	Pad     uint16
}

type netkerMetricsVal struct {
	_       structs.HostLayout
	Packets uint64
	Bytes   uint64
}

// loadNetker returns the embedded CollectionSpec for netker.
func loadNetker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetkerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load netker: %w", err)
	}

	return spec, err
}

// loadNetkerObjects loads netker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*netkerObjects
//	*netkerPrograms
//	*netkerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetkerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// netkerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netkerSpecs struct {
	netkerProgramSpecs
	netkerMapSpecs
	netkerVariableSpecs
}

// netkerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netkerProgramSpecs struct {
	NkFromContainer *ebpf.ProgramSpec `ebpf:"nk_from_container"`
	NkToContainer   *ebpf.ProgramSpec `ebpf:"nk_to_container"`
}

// netkerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netkerMapSpecs struct {
	NetkerEndpoints *ebpf.MapSpec `ebpf:"netker_endpoints"`
	NetkerMetrics   *ebpf.MapSpec `ebpf:"netker_metrics"`
}

// netkerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netkerVariableSpecs struct {
}

// netkerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type netkerObjects struct {
	netkerPrograms
	netkerMaps
	netkerVariables
}

func (o *netkerObjects) Close() error {
	return _NetkerClose(
		&o.netkerPrograms,
		&o.netkerMaps,
	)
}

// netkerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type netkerMaps struct {
	NetkerEndpoints *ebpf.Map `ebpf:"netker_endpoints"`
	NetkerMetrics   *ebpf.Map `ebpf:"netker_metrics"`
}

func (m *netkerMaps) Close() error {
	return _NetkerClose(
		m.NetkerEndpoints,
		m.NetkerMetrics,
	)
}

// netkerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type netkerVariables struct {
}

// netkerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type netkerPrograms struct {
	NkFromContainer *ebpf.Program `ebpf:"nk_from_container"`
	NkToContainer   *ebpf.Program `ebpf:"nk_to_container"`
}

func (p *netkerPrograms) Close() error {
	return _NetkerClose(
		p.NkFromContainer,
		p.NkToContainer,
	)
}

func _NetkerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netker_bpf_bpfel.o
var _NetkerBytes []byte
